### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by Muyfa666** [isage/nxengine-evo#13] opened 2017-03-04 14:38 UTC
The game freezes if I change resolution in full screen. In windowed mode all is good.

This is with v2.4

Win10 Pro x64 running.

**Comment by isage** [comment] 2017-03-04 14:46
Can't reproduce. 
Can you provide debug.txt from /Users/<your-user>/Application Data/nxengine/nxengine-evo
Also, from which resolution and to which are you switching? Does this occur with any resolution?
Are you using 64bit version? If so, does this occur in 32bit version too?

**Comment by Muyfa666** [comment] 2017-03-04 17:38
I get very much garbage graphics when changing, but you're spot on. This does not seem to happen with Win32, only Win64.

I see no debug.txt in my user app dir thou.

**Comment by isage** [comment] 2017-03-04 21:25
Sorry, on Win10 that should be  /Users/[your-user]/AppData/Roaming/nxengine/nxengine-evo
I've reproduced this, though.
It doesn't really freeze, just stops drawing.
I'll try to fix this in the next release.

**Comment by Muyfa666** [comment] 2017-03-05 10:27
Great. :-)

**Comment by isage** [comment] 2017-03-05 12:08
Can you try with this binary http://rgho.st/6mvNsWNZ2 ?

**Comment by isage** [comment] 2017-03-05 12:17
Oh, wait, disregard that. That's a debug version, but i forgot to include debug dlls

**Comment by isage** [comment] 2017-03-05 12:34
http://transfer.sh/11gpSM/nx-x64.exe try this one.

**Comment by Muyfa666** [comment] 2017-03-05 15:42
Seem to work fine now. :-)

**Comment by isage** [comment] 2017-04-27 20:28
Fixed in latest release

**Closed by isage** 2017-04-27 20:28 UTC
